### ISSUE TITLE
Debugging of UEI gateway issue

### ISSUE THREAD

**Issue by prasad-takale-eminds** [beckn/beckn-onix#164]
## Description
The UEI gateway was not getting deployed on UEI infra. 

## Goals
- [ ] Identify the root cause of the connectivity issues.
- [ ] Implement a fix to resolve the connectivity issues.
- [ ] Ensure the gateway operates without interruptions.
- [ ] Document the debugging and resolution process.

## Expected Outcome
The UEI gateway should function without any connectivity issues, ensuring reliable data transmission across the Beckn platform.

## Acceptance Criteria
- [ ] The root cause of the issue is identified and documented.
- [ ] A fix is implemented and tested.
- [ ] Detailed documentation of the debugging process and resolution is provided.

## Mockups / Wireframes
N/A

## Product Name
Beckn

## Domain
UEI

## Tech Skills Needed
- Network debugging
- Gateway configuration
- Data transmission protocols
- System monitoring and logging

## Complexity
High

## Category
Bug

## Sub Category
Connectivity Issues

**Comment by prasad-takale-eminds** [comment]
UEI team was deploying the Gateway on there infra. But they were getting below error. 

```
java.lang.NullPointerException: Cannot invoke "in.succinct.onet.core.adaptor.NetworkAdaptor$Domain.getExtensionPackage()" because the return value of "in.succinct.onet.core.adaptor.NetworkAdaptor$Domains.get(String)" is null
    at in.succinct.onet.core.adaptor.NetworkAdaptor.create(NetworkAdaptor.java:518)
    at in.succinct.onet.core.adaptor.NetworkAdaptor$5$1.create(NetworkAdaptor.java:558)
    at in.succinct.json.JSONAwareWrapper.get(JSONAwareWrapper.java:143)
    at in.succinct.json.JSONAwareWrapper.get(JSONAwareWrapper.java:124)
    at in.succinct.beckn.Request.getContext(Request.java:42)
    at in.succinct.beckn.gateway.controller.BgController.act(BgController.java:244)
    at in.succinct.beckn.gateway.controller.BgController.search(BgController.java:263)
```
We have check the same issue on our infra and we were also getting the same issue. 
After debugging further we got to know that automic registry was down due to which gateway was not getting deployed.

To fix this issue Venky suggested to remove networks folder from the code and rebuild the docker image. 
We did the required change on gateway build machine and rebuild the docker image the push it to the docker hub. 
With the latest docker image we successfully deployed gateway  on UEI infra.
