### ISSUE TITLE
Error during installation of registry

### ISSUE THREAD

**Issue by vbabuEM** [beckn/beckn-onix#52]
When installing registry for the first time, we get the following error:
```
What would you like to do?
1. Join an existing network
2. Create new production network
3. Set up a network on your local machine
4. Merge multiple networks
5. Configure Existing Network
(Press Ctrl+C to exit)
Enter your choice: 2
Great choice! Get ready.

Which platform would you like to set up?
1. Registry
2. Gateway
3. BAP
4. BPP
Enter your choice: 1
Proceeding with the setup for Registry...
Please provide the network-specific configuration URL.
Paste the URL of the network configuration here (or press Enter to skip): bhanu-test-reg.becknprotocol.io
Network configuration URL provided: bhanu-test-reg.becknprotocol.io
Enter publicly accessible registry URL: https://bhanu-test-reg.becknprotocol.io/
................Installing required packages................
Docker Bash completion is already installed.
docker-compose is already installed.
Package Installation is done
bhanu-test-reg.becknprotocol.io
registry_data_volume
registry_database_volume
cp: can't stat '/source/db.txt': No such file or directory
Untagged: busybox:latest
Untagged: busybox@sha256:c3839dd800b9eb7603340509769c43e146a74c63dca3045a8e7dc8ee07e53966
Deleted: sha256:ba5dc23f65d4cc4a4535bce55cf9e63b068eb02946e3422d3587e8ce803b6aab
Deleted: sha256:95c4a60383f7b6eb6f7b8e153a07cd6e896de0476763bef39d0f6cf3400624bd
................Installing Registry service................
Recreating registry ...

ERROR: for registry  'ContainerConfig'

ERROR: for registry  'ContainerConfig'
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 33, in <module>
    sys.exit(load_entry_point('docker-compose==1.29.2', 'console_scripts', 'docker-compose')())
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 81, in main
    command_func()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 203, in perform_command
    handler(command, command_options)
  File "/usr/lib/python3/dist-packages/compose/metrics/decorator.py", line 18, in wrapper
    result = fn(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1186, in up
    to_attach = up(False)
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1166, in up
    return self.project.up(
  File "/usr/lib/python3/dist-packages/compose/project.py", line 697, in up
    results, errors = parallel.parallel_execute(
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 108, in parallel_execute
    raise error_to_reraise
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 206, in producer
    result = func(obj)
  File "/usr/lib/python3/dist-packages/compose/project.py", line 679, in do
    return service.execute_convergence_plan(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 579, in execute_convergence_plan
    return self._execute_convergence_recreate(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 499, in _execute_convergence_recreate
    containers, errors = parallel_execute(
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 108, in parallel_execute
    raise error_to_reraise
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 206, in producer
    result = func(obj)
  File "/usr/lib/python3/dist-packages/compose/service.py", line 494, in recreate
    return self.recreate_container(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 612, in recreate_container
    new_container = self.create_container(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 330, in create_container
    container_options = self._get_container_create_options(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 921, in _get_container_create_options
    container_options, override_options = self._build_container_volume_options(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 960, in _build_container_volume_options
    binds, affinity = merge_volume_bindings(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 1548, in merge_volume_bindings
    old_volumes, old_mounts = get_container_data_volumes(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 1579, in get_container_data_volumes
    container.image_config['ContainerConfig'].get('Volumes') or {}
KeyError: 'ContainerConfig'
Registry installation successful
[Installation Logs]
Your Registry setup is complete.
You can access your Registry at https://bhanu-test-reg.becknprotocol.io/
Process complete. Thank you for using Beckn-ONIX!
```

**Comment by vbabuEM** [comment]
I did the following:
1. Fixed an error where the registry_data_volume was mapped instead of registry_database_volume
2. Added check to remove the db.txt file not available error.
3. The gateway volumes were getting created on registry. Since we support individual deployments, we need individual docker files. So created separate files for gateway and registry (and also bap and bpp)
4. Removed network configuration question at the beginning. We do not do anything with the response. Its just confusing as seen in the screenshot in the issue above.
